version: '3'
services:
  frontend:
    container_name: frontend-vue
    build: ./src/frontend
    image: frontend-vue:latest
    ports:
      - 8090:80
    volumes:
      - ./src/frontend:/app
      - ./src/frontend/node_modules:/app/node_modules

  nginx:
    container_name: nginx
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
    volumes:
      - ./src/frontend:/usr/share/nginx/html
      - ./src/backend/default.conf:/etc/nginx/conf.d/default.conf

  backend:
    container_name: backend
    build: ./src/backend
    image: backend:latest
    ports:
      - 8082:8082
    volumes:
      - ./src/backend:/app
    command: python app.py
